
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozountbkleokvfqcwjui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96b3VudGJrbGVva3ZmcWN3anVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNzkxMDQsImV4cCI6MjA2MjY1NTEwNH0.cpv14i9tUKNHUl0lOEItUjbs9MB-G8TLaZlk_giO3Ug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
